name: Bank

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master", "feature/*" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform-agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo chmod +x ./bank/scripts/install_dependencies.sh
          /bin/bash ./bank/scripts/install_dependencies.sh

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: | 
          cd bank
          cmake -B ${{github.workspace}}/bank/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Bank
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/bank/build/ --config ${{env.BUILD_TYPE}}

      - name: Test Bank
        working-directory: ${{github.workspace}}/bank/build/
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C --extra-verbose --output-on-failure  ${{env.BUILD_TYPE}}

      - name: Compute Test Coverage
        working-directory: ${{github.workspace}}/bank/
        run: |
          sudo chmod +x scripts/compute_test_coverage.sh
          /bin/bash scripts/compute_test_coverage.sh

      - name: Install Bank As WebApp
        working-directory: ${{github.workspace}}/bank
        run: |
          sudo chmod +x scripts/install_web_app.sh
          /bin/bash scripts/install_web_app.sh
    
      # sudo chmod +x tests/test_user_acc_load.sh
      - name: Test Bank As WebApp
        working-directory: ${{github.workspace}}/bank
        run: |
          sudo chmod +x tests/test_http_get.sh
          /bin/bash tests/test_http_get.sh
          sudo chmod +x tests/test_send_email.sh
          /bin/bash tests/test_send_email.sh
          
          /bin/bash tests/test_user_acc_load.sh
          
